set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

if(NOT DEFINED RK3576_GCC_COMPILER_PREFIX)
  if(DEFINED ENV{GCC_COMPILER})
    set(RK3576_GCC_COMPILER_PREFIX "$ENV{GCC_COMPILER}")
  else()
    set(RK3576_GCC_COMPILER_PREFIX "/home/parker/Projects/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu")
  endif()
endif()

set(CMAKE_C_COMPILER "${RK3576_GCC_COMPILER_PREFIX}-gcc")
set(CMAKE_CXX_COMPILER "${RK3576_GCC_COMPILER_PREFIX}-g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
